import { TCategory } from "./Categories.types";
// export const CategoriesMock: TCategory[] = [
//   {
//     id: "1",
//     creatorId: "1",
//     name: "Business",
//     color: "blue",
//     members: [],
//     taskCount: 40,
//     completedTaskCount: 20,
//   },
// ];
export const CategoriesMock: TCategory[] = [
  {
    id: "1",
    creatorId: "1",
    name: "Business",
    color: "blue",
    members: [],
    taskCount: 40,
    completedTaskCount: 20,
  },
  {
    id: "2",
    creatorId: "1",
    name: "Personal",
    color: "violet",
    members: [],
    taskCount: 18,
    completedTaskCount: 6,
  },
  {
    id: "3",
    creatorId: "1",
    name: "Groceries",
    color: "pink",
    members: [],
    taskCount: 40,
    completedTaskCount: 10,
  },
  {
    id: "4",
    creatorId: "1",
    name: "Work",
    color: "violet",
    members: [],
    taskCount: 18,
    completedTaskCount: 3,
  },
  {
    id: "5",
    creatorId: "1",
    name: "Daily routine",
    color: "blue",
    members: [],
    taskCount: 40,
    completedTaskCount: 20,
  },
  {
    id: "6",
    creatorId: "1",
    name: "Business",
    color: "pink",
    members: [],
    taskCount: 40,
    completedTaskCount: 20,
  },
  {
    id: "7",
    creatorId: "1",
    name: "Personal",
    color: "violet",
    members: [],
    taskCount: 40,
    completedTaskCount: 20,
  },
  {
    id: "8",
    creatorId: "1",
    name: "Groceries",
    color: "aqua",
    members: [],
    taskCount: 40,
    completedTaskCount: 20,
  },
  {
    id: "9",
    creatorId: "2",
    name: "Work",
    color: "blue",
    members: [],
    taskCount: 40,
    completedTaskCount: 20,
  },
  {
    id: "10",
    creatorId: "2",
    name: "Daily routine",
    color: "blue",
    members: [],
    taskCount: 40,
    completedTaskCount: 20,
  },
];
